version: "3.9"
   
services:
  redis:
    image: redis
    ports:
      - "6379"

  creator:
    build: creator
    image: k3d-registry.localhost:5000/creator:latest
    environment:
      - REDIS_SERVICE_HOST=redis
    links:
      - "redis:redis"
    
  worker:
    build: worker
    image: k3d-registry.localhost:5000/worker:latest
    environment:
      - REDIS_SERVICE_HOST=redis
    links:
      - "redis:redis"